# Generated by Django 4.1.2 on 2022-11-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('napr', models.CharField(max_length=3, verbose_name='Направление')),
                ('product_code', models.CharField(max_length=10, verbose_name='Товарный код')),
                ('product_type', models.CharField(max_length=400, verbose_name='Тип товара')),
                ('month', models.CharField(max_length=3, verbose_name='Месяц')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('id_country', models.CharField(max_length=3, verbose_name='Код страны')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('edizm', models.CharField(max_length=150, verbose_name='Единицы измерения')),
                ('edizm_name', models.CharField(max_length=150, verbose_name='Единицы измерения по РУ')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('weight', models.FloatField(verbose_name='Масса')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('region', models.CharField(max_length=300, verbose_name='Регион')),
                ('federal_district', models.CharField(max_length=300, verbose_name='Фед округ')),
            ],
            options={
                'verbose_name': 'База данных',
                'verbose_name_plural': 'Базы данных',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория'),
        ),
    ]
