# Generated by Django 4.1.2 on 2022-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_database1_alter_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tnved_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4, verbose_name='Ключ')),
                ('value', models.CharField(max_length=400, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
            },
        ),
    ]
