# Generated by Django 4.1.2 on 2022-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tnved_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved_type',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='Значение'),
        ),
    ]
