# Generated by Django 4.1.2 on 2022-11-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tnved_type_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='tnved_types_rate_grouped1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(verbose_name='Имя')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
            ],
        ),
    ]
